# Generated by Django 4.2 on 2025-11-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
