# Generated by Django 4.2 on 2025-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
